Improve the error message when loading an empty workspace.yaml
Summary:
Before:

```
dagster.check.ParameterCheckError: Param "workspace_config" is not one of ['dict', 'frozendict']. Got None which is type <class 'NoneType'>.
```

After:
```
dagster.check.ParameterCheckError: Param "workspace_config" is not one of ['dict', 'frozendict']. Got None which is type <class 'NoneType'>. Could not parse a valid workspace config from the yaml file at workspace.yaml
```

Test Plan: Unit

Reviewers: sandyryza, dgibson, alangenfeld, sashank, yuhan

Reviewed By: sashank

Differential Revision: https://dagster.phacility.com/D4708