update stress tests for grpc limit repro
Test Plan:
trying to subset the 2500_nodes job causes
```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.RESOURCE_EXHAUSTED
	details = "Received message larger than max (5276540 vs. 4194304)"
	debug_error_string = "{"created":"@1627401619.021592000","description":"Received message larger than max (5276540 vs. 4194304)","file":"src/core/ext/filters/message_size/message_size_filter.cc","file_line":208,"grpc_status":8}"
>
```

Reviewers: dgibson

Reviewed By: dgibson

Differential Revision: https://dagster.phacility.com/D9082