Make error handling for dynamically loading functions more precise
Summary:
This codepath followed the Pythonic "pattern" of using exceptions for error-handling control flow
instead of checking for error conditions up front. As often happens, this ends up masking *unexpected*
errors, leading to misleading error messages.

This changes thie codepath to use a LBYL (Look Before You Leap) pattern which ends up only communicating
the error message when the precise condition is applied.

This also fixes the error that tripped up @bengotow

Test Plan:
```
(dagster-dev-3.7.6) [schrockn@mbp ~/code/dagster/examples/fan_in_pipeline (when-keeping-it-pythonic-goes-wrong *)]$ dagit
/Users/schrockn/code/dagster/python_modules/dagster/dagster/cli/workspace/cli_target.py:59: UserWarning: You are automatically loading a "repository.yaml", a deprecated capability. This capability will be eliminated in 0.9.0.
  'You are automatically loading a "repository.yaml", a deprecated '
/Users/schrockn/code/dagster/python_modules/dagster/dagster/cli/workspace/load.py:36: UserWarning: You are using the legacy repository yaml format. Please update your file to abide by the new workspace file format.
  'You are using the legacy repository yaml format. Please update your file '
Traceback (most recent call last):
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/bin/dagit", line 11, in <module>
    load_entry_point('dagit', 'console_scripts', 'dagit')()
  File "/Users/schrockn/code/dagster/python_modules/dagit/dagit/cli.py", line 177, in main
    cli(auto_envvar_prefix='DAGIT')  # pylint:disable=E1120
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/schrockn/code/dagster/python_modules/dagit/dagit/cli.py", line 85, in ui
    host_dagit_ui(host, port, storage_fallback, port_lookup, **kwargs)
  File "/Users/schrockn/code/dagster/python_modules/dagit/dagit/cli.py", line 89, in host_dagit_ui
    workspace = get_workspace_from_kwargs(kwargs)
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/cli/workspace/cli_target.py", line 104, in get_workspace_from_kwargs
    return workspace_from_load_target(created_workspace_load_target(kwargs))
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/cli/workspace/cli_target.py", line 90, in workspace_from_load_target
    return load_workspace_from_yaml_path(load_target.path)
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/cli/workspace/load.py", line 27, in load_workspace_from_yaml_path
    return load_workspace_from_config(workspace_config, yaml_path)
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/cli/workspace/load.py", line 42, in load_workspace_from_config
    pointer=CodePointer.from_legacy_repository_yaml(yaml_path)
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/core/host_representation/handle.py", line 27, in create_in_process_location
    repo_def = repository_def_from_pointer(pointer)
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/core/definitions/reconstructable.py", line 308, in repository_def_from_pointer
    target = def_from_pointer(pointer)
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/core/definitions/reconstructable.py", line 287, in def_from_pointer
    return _check_is_loadable(target())
  File "/Users/schrockn/code/dagster/examples/fan_in_pipeline/repo.py", line 23, in define_repository
    return RepositoryDefinition("fan_in_pipeline", pipeline_defs=[fan_in_pipeline])
TypeError: __init__() got an unexpected keyword argument 'pipeline_defs
```

Reviewers: prha, bengotow

Reviewed By: prha

Subscribers: bengotow

Differential Revision: https://dagster.phacility.com/D3536