Exit gracefully with informative message when no arguments are passed
Summary:
Alternatively, we could set required=True in the click argument. This would give:
```
➜  Desktop dagster schedule start
Usage: dagster schedule start [OPTIONS] SCHEDULE_NAME...
Try "dagster schedule start --help" for help.

Error: Missing argument "SCHEDULE_NAME...".
```
See: https://click.palletsprojects.com/en/7.x/arguments/#variadic-arguments

Test Plan: Manual

Reviewers: sashank, prha

Reviewed By: sashank

Differential Revision: https://dagster.phacility.com/D2351